source 'https://github.com/CocoaPods/Specs.git'
workspace 'Tesseract-OCR-iOS'
xcodeproj 'TestsProject/TestsProject.xcodeproj/', 'Coverage' => :debug

target 'TestsProjectTests' do
	pod 'SVProgressHUD'

end
